#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d  󰈹   󰺵 

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox desktop='^2' follow=on focus=on
bspc rule -a codium desktop='^3' follow=on focus=on

$HOME/.config/polybar/launch.sh
feh --bg-fill $HOME/.inst/wallpapers/wallpaper.jpg

pkill picom
picom -f --daemon &
