#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d  󰈹   󰺵 

bspc config border_width         0
bspc config window_gap           8

bspc config split_ratio          4
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Firefox desktop='^2' follow=on
bspc rule -a codium desktop='^3' follow=on

$HOME/.config/polybar/launch.sh

feh --bg-fill $HOME/.inst/wallpapers/wallpaper.jpg

pkill picom
picom -f --daemon &
