import = []

live_config_reload = true

[window]
opacity = 0.90
padding = { x = 10, y = 10 }
dynamic_padding = true

[font]
size = 12
builtin_box_drawing = true
normal = { family = "Cousine Nerd Font", style = "Regular" }
bold = { family = "Cousine Nerd Font", style = "Bold" }
italic = { family = "Cousine Nerd Font", style = "Italic" }
offset = { x = 0, y = 4 }

[colors.primary]
foreground = "#D3DBE0"
background = "#171719"

